config/routes.rb
Rails.application.routes.draw do
  root 'cities#index'
  resources :cities, only: [:index, :show]
  resources :leagues, except: [:index, :destroy]
  delete "/leagues/:id", to: "leagues#destroy", as: "destroy"

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy', as: 'logout'

  post '/teams/:id/add_to_teams', to: 'teams#add_to_teams', as: "add_to_teams"

  get "/cities/:id/new", to: "leagues#new_in_city", as: "new_in_city"

  get "/leagues/:id/new", to: "teams#join_league", as: "join_league"

  post "/teams/:id/", to: "teams#join_league_create"

  post "/teams/:id/payment", to: "teams#payment", as: "payment"

  resources :teams, only: [:new, :create, :show]

  get "/popular/:id", to: "cities#popular", as: "most_popular"

  get "/players/current", to: "players#current_player", as: "current_player"

  resources :players, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :leagues

  def most_popular
    self.leagues.max_by{|l| l.teams.count}
  end
end

app/models/league.rb
class League < ApplicationRecord
  has_many :teams
  belongs_to :city

  validates(:name, {presence: true, uniqueness: true}
  )
  validates :sport, inclusion: { in: %w(Soccer Basketball Softball Kickball Dodgeball Volleyball Hockey Football)}

  validates :day_of_week, inclusion: { in: %w(Monday Tuesday Wednesday Thursday Friday Saturday Sunday), message: "%{value} is not a valid day of the week." }
  validates :cost, numericality: { greater_than_or_equal_to: 100, less_than_or_equal_to: 1000 }
  validates :level, inclusion: { in: %w(Beginner Intermediate Experienced), message: " must be 'Beginner', 'Intermediate' or 'Experienced.'"}


end

app/models/player.rb
class Player < ApplicationRecord
  has_many :team_players
  has_many :teams, through: :team_players

  validates(:name, {presence: true, uniqueness: true})
  validates(:email, {presence: true, uniqueness: true})
  validates_format_of :email, :with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  validate :check_for_full_name

  def check_for_full_name
    if name.split.size < 2
      errors.add(:name, "^Please write your full name")
    end
  end

end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :league
  has_many :team_players
  has_many :players, through: :team_players

  validates :name, { presence: true, length: { minimum: 5} }

end

app/models/team_player.rb
class TeamPlayer < ApplicationRecord
  belongs_to :team
  belongs_to :player
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :is_logged_in

  def current_user
    @current_user = Player.find_by({ id: session[:user_id] })
  end

  def is_logged_in
    current_user != nil
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
    if params[:search]
      @leagues = League.all.where("city_id = ?", @city.id).where("sport LIKE ?", params[:search])
    else
      @leagues = @city.leagues
    end
  end

  def popular
    @city = City.find(params[:id])
    @league = @city.most_popular
    redirect_to @league
  end

end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

  def index
    @leagues = League.all
  end

  def new
    @league = League.new
  end

  def create
    @league = League.create(league_params)

    if @league.valid?
      redirect_to @league
    else
      @errors = @league.errors.full_messages
      render :new
    end
  end

  def show
    @league = League.find(params[:id])
    @image_url = "/assets/" + @league.sport.downcase + ".jpg"
  end

  def new_in_city
    @city = City.find(params[:id])
    @league = League.new

    render :new_in_city

    if @league.valid?
      redirect_to @league
    else
      @errors = @league.errors.full_messages
    end
  end

  def popular
    @league = League.most_popular

    redirect_to @league
  end

  def edit
    @league = League.find(params[:id])
  end

  def update
    @league = League.find(params[:id])

    if @league.valid?
      @league.update(league_params)
      redirect_to @league
    else
      @errors = @league.errors.full_messages
      render :edit
    end
  end

  def destroy
    @league = League.find(params[:id])
    @city = @league.city
    @league.delete

    redirect_to city_path(@city)
  end

  private

  def league_params
    params.require(:league).permit(:name, :sport, :day_of_week, :cost, :level, :city_id)
  end


end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def new
    @player = Player.new
  end

  def create
    @player = Player.create(player_params)

    if @player.valid?
      session[:user_id] = @player.id
      redirect_to @player
    else
      @errors = @player.errors.full_messages
      render :new
    end
  end

  def show
    @player = Player.find(params[:id])
  end

  def current_player
    @player = Player.find_by({ id: session[:user_id] })
    render :show
  end

  private

  def player_params
    params.require(:player).permit(:name, :email, :team_ids)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @player = Player.find_by(name: params[:session][:name])
    if params[:session][:email] == @player.email
      session[:user_id] = @player.id
      redirect_to player_path(@player)
    else
      flash[:danger] = 'Invalid name/email combination'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    render 'new'
  end

end

app/controllers/team_players_controller.rb
class TeamPlayersController < ApplicationController
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def show
    @team = Team.find(params[:id])
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.create(team_params)

    if @team.valid?
      redirect_to @team
    else
      @errors = @team.errors.full_messages
      render :new
    end
  end

  def payment
    @team = Team.find(params[:id])

    @team.update(paid: true)

    redirect_to @team
  end

  def join_league
    @league = League.find(params[:id])
    @team = Team.new
  end

  def join_league_create
    @league = League.find(params[:id])
    @team = Team.create(team_params)

    if @team.valid?
      redirect_to @team
    else
      @errors = @team.errors.full_messages
      render :join_league
    end
  end

  def add_to_teams
    @team = Team.find(params[:id])
    @player = Player.find(session[:user_id])
    @player.teams << @team
    redirect_to player_path(@player)
  end

  private

  def team_params
    params.require(:team).permit(:name, :paid, :league_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/team_players_helper.rb
module TeamPlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/cities/index.erb
<div class="container-fluid">
  <nav class="navbar navbar-default justify-content-between">
    <h1 class="navbar-brand">BlogSports</h1>
    <nav class="nav justify-content-center">
      <% if is_logged_in -%>
        <a class="nav-link"><%= link_to "Log Out", logout_path, method: "delete" %></a>
      <% else -%>
        <a class="nav-link"><%= link_to "Sign In", login_path %></a>
      <% end -%>
      <a class="nav-link"><%= link_to "Create a League", new_league_path %></a>
    </nav>
  </nav>
</div>

<div class="parent">
  <% @cities.each do |city| %>
    <%= div_for(city, class: "card") do %>
      <div class="card-header">
        <%= link_to city.name, city_path(city), class: 'city-name' %>
      </div>
      <div class="card-body">
      </div>
    <% end %>
  <% end %>
</div>

app/views/cities/show.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <h1><%= @city.name %> Leagues<h1>
    </div>
    <nav class="nav justify-content-center">
      <a class="nav-link"><%= link_to "Most Popular League", most_popular_path(@city) %></a>
      <a class="nav-link"><%= link_to "Main Menu", cities_path %></a>
      <a class="nav-link"><%= link_to "My Profile", current_player_path %></a>
    </nav>
  <form class="form-inline">
    <%= form_tag(city_path, method: :get) do %>
      <div class="form-group">
        <%= text_field_tag :search, params[:search], class: 'form-control' %>
      <div>
        <%= submit_tag 'Search By Sport', name: nil %>
      <% end %>
  </form>
  </div>
</nav>

<div class="container-fluid">
  <div class="row">
  <% @leagues.each do |league| %>
    <div class="col-xs-12 col-md-4 my-3">
    <%= div_for(league, class: "card") do %>
      <div style="display:none"><%=  @image_url = "/assets/" + league.sport.downcase + ".jpg"%></div>
        <img class="card-img-top" src=<%= @image_url %> alt="Sport photo">
        <div class="card-block">
          <h2 class="card-text text-center"><%= link_to league.name, league_path(league) %></h2>
        </div>
    <% end %>
  </div>
  <% end %>
</div>

<div class="container-fluid">
  <div class="row">
    <h5>Don't see the league you want to join?</h5>
  </div>
  <div class="btn btn-primary">
    <a><%= link_to "Start a New League in #{@city.name}", new_in_city_path(@city), :class => "btn" %></a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Sports</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  
</html>

app/views/leagues/new.erb
<div class="container-fluid">
  <h1>Create a New League </h1>
</div>

<div class="container-fluid">
  <ul>
    <% if @errors %>
      <% @errors.each do |error| %>
      <li> <%= error %> </li>
      <% end %>
    <% end%>
  </ul>
</div>

<div class="container-fluid">
  <%= form_for @league do |f| %>
    <%= f.label :city_id %>
    <%= f.collection_select(:city_id, City.all, :id, :name) %><br><br>
    <%= f.label :name %>
    <%= f.text_field :name %><br><br>
    <%= f.label :sport %>
    <%= f.select :sport, %w(Soccer Basketball Softball Kickball Dodgeball Volleyball Hockey Football) %><br><br>
    <%= f.label :day_of_week %>
    <%= f.select :day_of_week, ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"] %><br><br>
    <%= f.label :cost %>
    <%= f.number_field :cost %><br><br>
    <%= f.label :level %>
    <%= f.select :level, ["Beginner", "Intermediate", "Experienced"] %><br><br>
    <%= f.submit %>

    <% end %>
</div>

app/views/leagues/new_in_city.erb
<div class="container-fluid">
  <h1>Create a New League in <%= @city.name %> </h1>
</div>

<div class="container-fluid">
  <ul>
    <% if @errors %>
      <% @errors.each do |error| %>
      <li> <%= error %> </li>
      <% end %>
    <% end%>
  </ul>
</div>

<div class="container-fluid">
  <%= form_for @league, :html => {:class => "form"} do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control w-25" %>
    <div class="dropdown">
      <%= f.label :sport %><br>
      <%= f.select :sport, %w(Soccer Basketball Softball Kickball Dodgeball Volleyball Hockey Football), {class: "dropdown-menu"} %>
    </div>
    <div class="dropdown">
      <%= f.label :day_of_week %><br>
      <%= f.select :day_of_week, ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"], {class: "dropdown-menu"} %>
    </div>
    <div class="form-group">
      <%= f.label :cost %>
      <%= f.number_field :cost, class: "form-control w-25", type: "number" %>
    </div>
    <div class="dropdown">
      <%= f.label :level %><br>
      <%= f.select :level, ["Beginner", "Intermediate", "Experienced"] %>
    </div>
    <%= f.hidden_field :city_id, :value => @city.id %><br><br>
    <%= f.submit "Create League", class: "btn btn-default btn-primary" %>
  <% end %>
</div>

app/views/leagues/show.erb
<div class="container-fluid">
  <div class="card mx-auto w-50">
    <img class="card-img-top" src=<%= @image_url %> alt="Sport photo">
    <div class="card-body">
      <h1 class="card-title"><%= @league.name.split.map(&:capitalize).join(' ') %></h1>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">City: <%= @league.city.name %></li>
      <li class="list-group-item">Cost: $<%= @league.cost %></li>
      <li class="list-group-item">Experience Level: <%= @league.level %> </li>
    </ul>
    <% if @league.teams.size > 0 %>
      <div class="card-body">
      <h4 class="card-text">Teams</h4>

      <% @league.teams.each do |team| %>
      <ul>
        <li><%= link_to team.name, team_path(team) %></li>
      </ul>
      <% end %>
      </div>
      <div class="btn btn-lg btn-primary">
        <a><%= link_to "Create a New Team in This League", join_league_path, :class => "btn" %></a>
      </div>

    <% else %>
    <div class="card-body">
      <h3><%= link_to "Be the first team to sign up!", join_league_path  %></h3>
    </div>
    <% end %><br>

  </div>
</div>
<br><br>

<div class="container-fluid text-center">
  <h5><%= link_to "Back", city_path(@league.city) %></h5>
</div>

app/views/players/new.erb
<div class="centered-container">
  <div class="container-fluid">
    <h2>Create a New Player Profile</h2>
  </div>

  <div class="container-fluid">
    <ul>
      <% if @errors %>
        <% @errors.each do |error| %>
        <li> <%= error %> </li>
        <% end %>
      <% end%>
    </ul>
  </div>

  <div class="container-fluid">
    <%= form_for @player do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %><br><br>
      <%= f.label :email %>
      <%= f.text_field :email %><br><br>
      <%= f.label :team %>
      <%= f.collection_select(:team_ids, Team.all, :id, :name)%><br><br>
      <%= f.submit %>

    <% end %>
  </div>
<div>

app/views/players/show.erb
<div class="container-fluid">
  <div class="card mx-auto w-50">
    <div class="card-body">
      <h2 class="card-title"><%= @player.name %></h2>
    </div>

    <div class="card-body">
        <h4 class="card-text">Teams</h4>
        <% @player.teams.each do |team| %>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= link_to team.name, team_path(team) %></li>
          </ul>
        <% end %>
    </div>


    <div class="card-body">
      <p class="card-text">Contact: <%= @player.email %></p>
    </div>
  </div>
</div>
<br><br>

<div class="container-fluid text-center">
  <h5><%= link_to "Back", cities_path %></h5>
</div>